version: "3.8"

services:
  gx_db:
    container_name: gx_db
    image: itzg/minecraft-server:latest
    volumes:
      - DB:/data
    env_file: gx_db.env
    restart: unless-stopped
    networks:
      - mc

volumes:
  DB: { }

networks:
  mc: